### ISSUE TITLE
2x scaling by super-resolution part

### ISSUE THREAD

**Issue by rose-jinyang** [misakshoyan/joint-motion-deblur-and-sr#1]
Hello
How are you?
Thanks for contributing to this project.
It seems that your super-resolution network was designed for ONLY 4x scaling.
Is it correct?
What should I change if I want ONLY 2x scaling?

**Comment by misakshoyan** [comment]
Hi
Thanks, I am fine.
I appreciate your interest in this project.

Yes, you are right, the SR network was designed for 4x scaling.
But you can easily change it for 2x scaling.
In the MPRNet_SR.py file:
1. In line 374, just change the  64 * 4 ** 2 to  64 * 2 ** 2.
2. In line 375: nn.PixelShuffle(4) -> nn.PixelShuffle(2)

Please see [PixelShuffle ](https://pytorch.org/docs/stable/generated/torch.nn.PixelShuffle.html)documentation for more details.

And, of course, the training and validation datasets should also be re-generated for 2x scaling.
For the [REDS](https://seungjunnah.github.io/Datasets/reds.html) dataset, you can bicubically downscale (2x) _train_sharp_ and _val_sharp_ images and generate your training dataset for 2x case. After that, please follow the [Data Preparation](https://github.com/misakshoyan/joint-motion-deblur-and-sr#data-preparation) steps on the project's GitHub page.
Or, you can use the [Val300](https://drive.google.com/drive/folders/1JX3_P1r08ME9_MusSflmWRNVaqv0gp0c) dataset instead of REDS:_val_sharp_, similar to this project.

Note: Since the REDS:_test_sharp_ images are not publicly available, the _val_sharp_ images should be used for validation and testing. In this project, _Val300_ is used for validation, _Val300_ and _val_sharp_ are used for testing.
You can find more information in the [paper](https://mpcs.sci.am/index.php/mpcs/article/view/699).

I hope these changes should be enough:)

Regards,
Misak

**Comment by rose-jinyang** [comment]
Thank you @misakshoyan
